<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
	  <Content Include="BubbleShop.API.http" />
	</ItemGroup>

	<ItemGroup>
		<!-- ASP.NET Core 10 -->
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.9" />

		<!-- Logging -->
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />

		<!-- Swagger -->
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BubbleShop.Application\BubbleShop.Application.csproj" />
		<ProjectReference Include="..\BubbleShop.Infrastructure\BubbleShop.Infrastructure.csproj" />
	</ItemGroup>

</Project>