<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<!-- Entity Framework Core 10 -->
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.9">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>


		<!-- Microsoft Extensions -->
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.9" />

		<!-- JWT -->
		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.19.1" />

		<!-- Polly -->
		<PackageReference Include="Polly" Version="8.7.0" />
		<PackageReference Include="Riok.Mapperly" Version="4.3.1" />

		<!-- Serilog -->
		<PackageReference Include="Serilog" Version="4.3.1" />

		<!-- Stripe -->
		<PackageReference Include="Stripe.net" Version="52.1.0" />

		<!-- Azure OpenAI -->
		<PackageReference Include="Azure.AI.OpenAI" Version="2.1.0" />

		<!-- Security -->
		<PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.9" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BubbleShop.Domain\BubbleShop.Domain.csproj" />
		<ProjectReference Include="..\BubbleShop.Application\BubbleShop.Application.csproj" />
	</ItemGroup>

</Project>